-- MySQL Script generated by MySQL Workbench
-- 11/23/15 08:35:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sgaaes
-- -----------------------------------------------------
-- Sistema de Gerenciamento de Atividades dos Alunos da Escola Sistêmica 

-- -----------------------------------------------------
-- Schema sgaaes
--
-- Sistema de Gerenciamento de Atividades dos Alunos da Escola Sistêmica 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgaaes` DEFAULT CHARACTER SET utf8 ;
USE `sgaaes` ;

-- -----------------------------------------------------
-- Table `sgaaes`.`equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`equipes` (
  `id` INT(5) ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Vai armazenar o id das equipes.',
  `nome_equipe` VARCHAR(45) NOT NULL COMMENT 'Vai armazenar os nomes das equipes.',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Nesta tabela irá conter os dados das equipes já registradas.';


-- -----------------------------------------------------
-- Table `sgaaes`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`turmas` (
  `id` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Vai armazenar o id das turmas.',
  `nome_turma` VARCHAR(45) NOT NULL COMMENT 'Vai armazenar os nomes das turmas .',
  `periodo` CHAR(3) NOT NULL COMMENT 'Vai armazenar os períodos das turmas.',
  `modalidade` CHAR(1) NOT NULL COMMENT 'Vai armazenar o nível de graduação (superior ou técnico.)',
  `status` CHAR(1) NOT NULL COMMENT 'Ira armazenar o status da turma que pode ser ativo ou inativo.',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Nesta tabela irá conter os dados das turmas registradas.';


-- -----------------------------------------------------
-- Table `sgaaes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`usuarios` (
  `id` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Vai armazenar o id dos usuários.',
  `login` VARCHAR(45) NOT NULL COMMENT 'Vai  armazenar o login dos  usuários.',
  `senha` VARCHAR(45) NOT NULL COMMENT 'Vai armazenar a senha cadastrada.',
  `permissao` CHAR(1) NOT NULL COMMENT 'Vai armzenar a permissão dos usuários.',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Nesta tabela irá conter os dados dos usuários já registrados.';


-- -----------------------------------------------------
-- Table `sgaaes`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`alunos` (
  `id` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Vai armazenar o id dos alunos cadastrados.',
  `usuarios_id` INT(6) UNSIGNED ZEROFILL NOT NULL COMMENT 'Vai armazenar as chaves primarias dos usuários.',
  `turmas_id` INT(4) UNSIGNED ZEROFILL NOT NULL COMMENT 'Vai armazenar as chaves primarias das turmas.',
  `equipes_id` INT(5) UNSIGNED ZEROFILL NULL COMMENT 'Vai armazenar a chave primaria das equipes.',
  `nome_aluno` VARCHAR(45) NOT NULL COMMENT 'Vai armazenar os nomes dos alunos cadastrados.',
  `epiteto` VARCHAR(45) NOT NULL COMMENT 'Vai armazenar os apelidos dos alunos.',
  `email` VARCHAR(90) NOT NULL COMMENT 'Vai armazenar os e-mails dos alunos cadastrados.',
  `foto` VARCHAR(100) NULL COMMENT 'Vai armazenar a foto de cada aluno.',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_alunos_turmas_idx` (`turmas_id` ASC)  COMMENT '',
  INDEX `fk_alunos_usuarios1_idx` (`usuarios_id` ASC)  COMMENT '',
  INDEX `fk_alunos_equipes1_idx` (`equipes_id` ASC)  COMMENT '',
  CONSTRAINT `fk_alunos_equipes1`
    FOREIGN KEY (`equipes_id`)
    REFERENCES `sgaaes`.`equipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_turmas`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `sgaaes`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sgaaes`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Nesta tabela irá conter os dados dos alunos já registrados.';


-- -----------------------------------------------------
-- Table `sgaaes`.`motivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`motivos` (
  `id` TINYINT(3) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Vai armazenar o id dos motivos.',
  `motivo` VARCHAR(45) NOT NULL COMMENT 'Vai armazenar os motivos.',
  `descricao` TEXT NULL COMMENT 'Armazenará a descrição de casos de uso.',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Nesta tabela irá conter os dados dos motivos já registrados.';


-- -----------------------------------------------------
-- Table `sgaaes`.`ajustes_de_ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`ajustes_de_ponto` (
  `id` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Vai armazenar o id dos ajustes de ponto.',
  `alunos_id` INT(6) UNSIGNED ZEROFILL NOT NULL COMMENT 'Vai armazenar as chaves primarias dos alunos.',
  `motivos_id` TINYINT(3) UNSIGNED ZEROFILL NULL COMMENT 'Vai armazenar as chaves primarias dos motivos.',
  `data_ajuste` DATE NOT NULL COMMENT 'Vai armazenar as datas dos ajustes de ponto.',
  `tipo` CHAR(2) NULL COMMENT 'Vai armazenar os tipos de ajustes de ponto.',
  `hora_entrada` TIME NULL DEFAULT NULL COMMENT 'Vai armazenar os horários de entradas dos alunos referentes aos ajustes de ponto.',
  `hora_saida` TIME NULL COMMENT 'Vai armazenar os horários de saídas dos alunos referentes aos ajustes de ponto.',
  `status_ajuste` CHAR(1) NOT NULL COMMENT 'Vai armazenar os status dos ajustes de ponto que são rejeitados, pendentes, solicitados e aceitos.',
  `observacao` TEXT NULL COMMENT 'Vai armazenar as observações referente aos ajustes de ponto.',
  `motivo_rejeicao` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Irá armazenar o motivo da rejeição de um ajuste',
  `data_envio` DATE NULL DEFAULT NULL COMMENT 'Irá armazenar a data em que o ajuste foi enviado.',
  `hora_envio` TIME NULL DEFAULT NULL COMMENT 'Vai armazenar o horário em que o ajuste foi enviado.',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_ajustes de ponto_motivos1_idx` (`motivos_id` ASC)  COMMENT '',
  INDEX `fk_ajustes de ponto_alunos1_idx` (`alunos_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ajustes de ponto_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `sgaaes`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ajustes de ponto_motivos1`
    FOREIGN KEY (`motivos_id`)
    REFERENCES `sgaaes`.`motivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Nesta tabela irá conter os dados dos ajustes de pontos efetuadas.';


-- -----------------------------------------------------
-- Table `sgaaes`.`orientadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`orientadores` (
  `id` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Vai armazenar o id dos orientadores.',
  `usuarios_id` INT(6) UNSIGNED ZEROFILL NOT NULL COMMENT 'Vai armazenar as chaves primarias de usuários.',
  `nome_orientador` VARCHAR(45) NOT NULL COMMENT 'Vai armazenar os nomes dos orientadores.',
  `email` VARCHAR(90) NOT NULL COMMENT 'Vai armazenar os e-mails dos orientadores.',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_orientadores_usuarios1_idx` (`usuarios_id` ASC)  COMMENT '',
  CONSTRAINT `fk_orientadores_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sgaaes`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Na tabela orientadores contém os dados necessários dos orientadores registrados.';


-- -----------------------------------------------------
-- Table `sgaaes`.`anotacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`anotacoes` (
  `id` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Vai armazenar o id das anotações.',
  `orientadores_id` INT(4) UNSIGNED ZEROFILL NOT NULL COMMENT 'Vai armazenar a chave primaria dos orientadores.',
  `data_anotacao` DATE NOT NULL COMMENT 'Vai armazenar a data das anotações efetuadas.',
  `classificacao` CHAR(3) NOT NULL COMMENT 'Vai armazenar as classificações das anotações tanto positiva,negativa ou neutra.',
  `anotacao` TEXT NOT NULL COMMENT 'Vai armazenar as anotações efetuadas a cada aluno ou equipe.',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_anotacoes_orientadores1_idx` (`orientadores_id` ASC)  COMMENT '',
  CONSTRAINT `fk_anotacoes_orientadores1`
    FOREIGN KEY (`orientadores_id`)
    REFERENCES `sgaaes`.`orientadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Nesta tabela vai conter os dados das anotações efetuadas.';


-- -----------------------------------------------------
-- Table `sgaaes`.`orientadores_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`orientadores_has_turmas` (
  `orientadores_id` INT(4) UNSIGNED ZEROFILL NOT NULL COMMENT 'Contém as chaves primárias dos orientadores.',
  `turmas_id` INT(4) UNSIGNED ZEROFILL NOT NULL COMMENT 'Contém as chaves primárias das turmas.',
  PRIMARY KEY (`orientadores_id`, `turmas_id`)  COMMENT '',
  INDEX `fk_orientadores_has_turmas_turmas1_idx` (`turmas_id` ASC)  COMMENT '',
  INDEX `fk_orientadores_has_turmas_orientadores1_idx` (`orientadores_id` ASC)  COMMENT '',
  CONSTRAINT `fk_orientadores_has_turmas_orientadores1`
    FOREIGN KEY (`orientadores_id`)
    REFERENCES `sgaaes`.`orientadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orientadores_has_turmas_turmas1`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `sgaaes`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Nesta tabela irá conter as chaves primárias dos orientadores e das turmas.';


-- -----------------------------------------------------
-- Table `sgaaes`.`alunos_has_anotacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`alunos_has_anotacoes` (
  `alunos_id` INT(6) UNSIGNED ZEROFILL NOT NULL COMMENT 'Contém as chaves primárias dos alunos.',
  `anotacoes_id` INT(6) UNSIGNED ZEROFILL NOT NULL COMMENT 'Contém as chaves primárias das anotações.',
  PRIMARY KEY (`alunos_id`, `anotacoes_id`)  COMMENT '',
  INDEX `fk_alunos_has_anotacoes_anotacoes1_idx` (`anotacoes_id` ASC)  COMMENT '',
  INDEX `fk_alunos_has_anotacoes_alunos1_idx` (`alunos_id` ASC)  COMMENT '',
  CONSTRAINT `fk_alunos_has_anotacoes_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `sgaaes`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_has_anotacoes_anotacoes1`
    FOREIGN KEY (`anotacoes_id`)
    REFERENCES `sgaaes`.`anotacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgaaes`.`equipes_has_anotacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgaaes`.`equipes_has_anotacoes` (
  `equipes_id` INT(5) ZEROFILL UNSIGNED NOT NULL COMMENT 'Contém a chave primária das equipes.',
  `anotacoes_id` INT(6) UNSIGNED ZEROFILL NOT NULL COMMENT 'Contém as chaves primárias das anotações.',
  PRIMARY KEY (`equipes_id`, `anotacoes_id`)  COMMENT '',
  INDEX `fk_equipes_has_anotacoes_anotacoes1_idx` (`anotacoes_id` ASC)  COMMENT '',
  INDEX `fk_equipes_has_anotacoes_equipes1_idx` (`equipes_id` ASC)  COMMENT '',
  CONSTRAINT `fk_equipes_has_anotacoes_equipes1`
    FOREIGN KEY (`equipes_id`)
    REFERENCES `sgaaes`.`equipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipes_has_anotacoes_anotacoes1`
    FOREIGN KEY (`anotacoes_id`)
    REFERENCES `sgaaes`.`anotacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Nesta tabela irá conter as chaves primárias tanto de equipe quanto anotações.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
